"""Broker-neutral trade-idea records, workflow, and audit trail.

First building block of the accepted staged-autonomy direction
(docs/PRE_MIGRATION_DECISION_FRAMEWORK.md): AI proposes complete trade-idea
records, humans approve them, and every state change lands in an append-only
audit log. No module in this slice may submit orders.
"""

from gpt_trader.features.trade_ideas.audit import (
    ActorType,
    AuditAction,
    AuditEvent,
    AuditIntegrityError,
    TradeIdeaAuditLog,
    new_event_id,
)
from gpt_trader.features.trade_ideas.baseline import (
    BaselineProposer,
    BaselineProposerConfig,
)
from gpt_trader.features.trade_ideas.budget import (
    DEFAULT_RISK_BUDGET,
    BudgetIntegrityError,
    BudgetLogEntry,
    RiskBudget,
    RiskBudgetLog,
)
from gpt_trader.features.trade_ideas.closeout import (
    CloseoutAttribution,
    CloseoutAttributionIntegrityError,
    CloseoutAttributionLog,
    CloseoutResolution,
    DuplicateCloseoutAttributionError,
    MaxLossSnapshot,
)
from gpt_trader.features.trade_ideas.eligibility import evaluate_eligibility, is_eligible
from gpt_trader.features.trade_ideas.models import (
    AutonomyMode,
    BrokerTicket,
    Confidence,
    ConfidenceLabel,
    EntryZone,
    MaxLoss,
    ProductType,
    SizingRecommendation,
    TicketStatus,
    TicketVenue,
    TimeHorizon,
    TradeDirection,
    TradeIdea,
    is_safe_decision_id,
)
from gpt_trader.features.trade_ideas.paper_reconciliation import (
    PAPER_RECONCILIATION_PROFILES,
    PaperFillEvent,
    PaperFillProfileError,
    PaperFillReconciler,
    PaperFillReconciliationEntry,
    PaperFillReconciliationReport,
    paper_fill_events_from_store_events,
    validate_paper_reconciliation_profile,
)
from gpt_trader.features.trade_ideas.policy import ApprovalPolicy, PolicyViolationError
from gpt_trader.features.trade_ideas.proposer import Proposer
from gpt_trader.features.trade_ideas.replay import (
    ReplayOutcome,
    ReplayReport,
    ReplayResult,
    ReplayRunnerConfig,
    ReplayScoringError,
    ScoringLevels,
    TradeIdeaReplayRunner,
    extract_numeric_scoring_levels,
    score_trade_idea,
)
from gpt_trader.features.trade_ideas.report import (
    build_trade_idea_track_record_report,
    format_trade_idea_track_record_report,
)
from gpt_trader.features.trade_ideas.service import (
    ACTOR_ENV_VAR,
    DEFAULT_IDEAS_ROOT,
    IDEAS_ROOT_ENV_VAR,
    DuplicateTradeIdeaError,
    PreApprovalBrokerTicketError,
    TradeIdeaListQuery,
    TradeIdeaListResult,
    TradeIdeaListSortKey,
    TradeIdeaQueryPage,
    TradeIdeaService,
    TradeIdeaView,
    UnknownTradeIdeaError,
    create_trade_idea_service,
    resolve_ideas_root,
    resolve_trade_idea_actor_id,
)
from gpt_trader.features.trade_ideas.snapshot import (
    MarketSnapshot,
    SnapshotIntegrityError,
    SymbolSeries,
)
from gpt_trader.features.trade_ideas.snapshot_builder import (
    HistoricalCandleSource,
    MarketSnapshotBuilder,
    MarketSnapshotBuildRequest,
    canonical_granularity,
    granularity_duration,
    market_snapshot_to_payload,
)
from gpt_trader.features.trade_ideas.store import TradeIdeaStore
from gpt_trader.features.trade_ideas.workflow import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    InvalidTransitionError,
    TradeIdeaState,
    validate_transition,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ACTOR_ENV_VAR",
    "DEFAULT_RISK_BUDGET",
    "DEFAULT_IDEAS_ROOT",
    "DuplicateCloseoutAttributionError",
    "DuplicateTradeIdeaError",
    "HistoricalCandleSource",
    "IDEAS_ROOT_ENV_VAR",
    "TERMINAL_STATES",
    "ActorType",
    "ApprovalPolicy",
    "AuditAction",
    "AuditEvent",
    "AuditIntegrityError",
    "AutonomyMode",
    "BaselineProposer",
    "BaselineProposerConfig",
    "BrokerTicket",
    "BudgetIntegrityError",
    "BudgetLogEntry",
    "CloseoutAttribution",
    "CloseoutAttributionIntegrityError",
    "CloseoutAttributionLog",
    "CloseoutResolution",
    "Confidence",
    "ConfidenceLabel",
    "EntryZone",
    "InvalidTransitionError",
    "MarketSnapshot",
    "MarketSnapshotBuilder",
    "MarketSnapshotBuildRequest",
    "MaxLoss",
    "MaxLossSnapshot",
    "PAPER_RECONCILIATION_PROFILES",
    "PaperFillEvent",
    "PaperFillProfileError",
    "PaperFillReconciliationEntry",
    "PaperFillReconciliationReport",
    "PaperFillReconciler",
    "PreApprovalBrokerTicketError",
    "PolicyViolationError",
    "ProductType",
    "Proposer",
    "ReplayOutcome",
    "ReplayReport",
    "ReplayResult",
    "ReplayRunnerConfig",
    "ReplayScoringError",
    "RiskBudget",
    "RiskBudgetLog",
    "ScoringLevels",
    "SizingRecommendation",
    "SnapshotIntegrityError",
    "SymbolSeries",
    "TicketStatus",
    "TicketVenue",
    "TimeHorizon",
    "TradeDirection",
    "TradeIdea",
    "TradeIdeaAuditLog",
    "TradeIdeaListQuery",
    "TradeIdeaListResult",
    "TradeIdeaListSortKey",
    "TradeIdeaQueryPage",
    "TradeIdeaReplayRunner",
    "TradeIdeaService",
    "TradeIdeaState",
    "TradeIdeaStore",
    "TradeIdeaView",
    "UnknownTradeIdeaError",
    "build_trade_idea_track_record_report",
    "canonical_granularity",
    "create_trade_idea_service",
    "evaluate_eligibility",
    "extract_numeric_scoring_levels",
    "format_trade_idea_track_record_report",
    "granularity_duration",
    "is_eligible",
    "is_safe_decision_id",
    "market_snapshot_to_payload",
    "new_event_id",
    "paper_fill_events_from_store_events",
    "resolve_ideas_root",
    "resolve_trade_idea_actor_id",
    "score_trade_idea",
    "validate_paper_reconciliation_profile",
    "validate_transition",
]
