post_only_offset_bps: 15
spread_filter_bps: 25
depth_requirement: 50000
rsi_confirmation: false
volatility_filter: NORMAL
size_ladder:
- 0.0001
- 0.0002
- 0.0005
retry_on_rejection: true
max_retries: 2
