# Canary Production Profile - Safe Testing Configuration
# Purpose: Initial production deployment with minimal risk exposure
#
# This profile implements multiple safety layers:
# 1. Tiny notional amounts (0.01 BTC max)
# 2. Reduce-only mode (no position increases)
# 3. Strict risk limits
# 4. Comprehensive event recording

profile_name: "canary"
environment: "production"
description: "Ultra-conservative production testing profile with minimal risk"

# Trading Configuration
trading:
  mode: "reduce_only"  # Can only reduce or close positions, cannot open new ones
  enabled_strategies:
    - "momentum"  # Start with single, well-tested strategy
  symbols:
    - "BTC-USD"  # Sandbox testing on spot

  # Position Sizing - EXTREMELY CONSERVATIVE
  position_sizing:
    max_position_size: 0.01  # 0.01 BTC maximum
    max_notional_value: 500  # $500 USD maximum notional
    position_size_pct: 0.001  # 0.1% of account per position
    use_kelly_criterion: false  # Disable advanced sizing initially

  # Order Limits
  order_limits:
    max_orders_per_minute: 2
    max_orders_per_hour: 20
    max_orders_per_day: 50
    min_order_interval_seconds: 30

  # Execution Settings
  execution:
    slippage_tolerance: 0.002  # 0.2% maximum slippage
    use_limit_orders: true
    market_order_fallback: false  # Never use market orders
    time_in_force: "IOC"  # Immediate or cancel only

# Risk Management - ULTRA STRICT
risk_management:
  # Daily Limits
  daily_loss_limit: 10.00  # $10 maximum daily loss
  daily_profit_target: 20.00  # Optional: stop if target hit
  max_trade_value: 100.00  # $100 maximum per trade (guardrail test)

  # Position Limits
  max_concurrent_positions: 1
  max_leverage: 1.0  # No leverage
  max_exposure_pct: 0.01  # 1% maximum account exposure
  symbol_position_caps:
    BTC-USD: 0.01  # 0.01 BTC maximum position size

  # Drawdown Controls
  max_drawdown_pct: 0.02  # 2% maximum drawdown
  trailing_stop_pct: 0.01  # 1% trailing stop on all positions

  # Circuit Breakers
  circuit_breakers:
    consecutive_losses: 2  # Stop after 2 consecutive losses
    hourly_loss_limit: 5.00  # $5 per hour maximum
    error_threshold: 3  # Stop after 3 errors
    stale_mark_seconds: 60  # Stop if marks are stale > 60s

  # Correlation Limits
  max_correlation: 0.7  # Not applicable with single symbol

# Monitoring & Alerting
monitoring:
  # Logging
  log_level: "DEBUG"  # Maximum verbosity
  log_all_orders: true
  log_all_fills: true
  log_all_errors: true

  # Event Recording
  event_store:
    enabled: true
    store_type: "postgresql"
    retention_days: 90
    record_types:
      - "orders"
      - "fills"
      - "positions"
      - "pnl"
      - "errors"
      - "risk_events"
      - "strategy_signals"

  # Metrics Collection
  metrics:
    enabled: true
    interval_seconds: 5
    export_prometheus: true
    export_datadog: false

  # Streaming Configuration (for soak test)
  streaming:
    enabled: true
    level: 1
    rest_poll_interval: 5.0

  # Alerting
  alerts:
    enabled: true
    channels:
      - type: "log"
        level: "WARNING"
      - type: "slack"
        webhook_url: "${SLACK_WEBHOOK_URL}"
        level: "ERROR"
      - type: "pagerduty"
        api_key: "${PAGERDUTY_API_KEY}"
        level: "CRITICAL"

    # Alert Conditions
    conditions:
      - name: "daily_loss_breach"
        threshold: 8.00  # Alert at 80% of daily limit
        severity: "WARNING"
      - name: "position_stuck"
        duration_minutes: 30
        severity: "WARNING"
      - name: "stale_marks"
        duration_seconds: 30
        severity: "ERROR"
      - name: "connection_lost"
        duration_seconds: 10
        severity: "CRITICAL"

# Performance Settings
performance:
  # Threading
  use_threading: false  # Single-threaded for predictability

  # Caching
  cache_quotes: true
  quote_cache_ttl_ms: 1000

  # Rate Limiting
  api_rate_limit_pct: 0.5  # Use only 50% of rate limits

# Validation & Safety Checks
validation:
  # Pre-flight Checks
  require_balance_check: true
  min_required_balance: 100.00
  require_connection_test: true
  require_strategy_validation: true

  # Runtime Checks
  validate_every_order: true
  validate_position_limits: true
  validate_risk_limits: true

  # Post-trade Checks
  reconcile_positions: true
  reconciliation_interval_seconds: 60

# Feature Flags
features:
  # Disabled Features for Safety
  auto_rebalancing: false
  portfolio_optimization: false
  ml_predictions: false
  advanced_orders: false

  # Enabled Safety Features
  dead_mans_switch: true
  emergency_liquidation: true
  reduce_only_mode: true

# Session Configuration
session:
  # Trading Hours (UTC) - 24/7 for soak test
  start_time: "00:00"
  end_time: "23:59"
  trading_days:
    - "monday"
    - "tuesday"
    - "wednesday"
    - "thursday"
    - "friday"
    - "saturday"
    - "sunday"

  # Session Limits
  max_session_duration_minutes: 1440  # 24 hours
  auto_shutdown_on_limit: false

# Broker Configuration
broker:
  provider: "coinbase"
  environment: "sandbox"  # Using sandbox for soak test

  # Connection Settings
  connection:
    timeout_seconds: 5
    max_retries: 3
    retry_delay_seconds: 1
    heartbeat_interval_seconds: 30

  # Order Configuration
  orders:
    default_time_in_force: "IOC"
    enable_post_only: false
    enable_reduce_only: true

# Data Configuration
data:
  # Market Data
  market_data_source: "coinbase"
  use_websocket: true
  use_rest_fallback: true

  # Historical Data
  historical_lookback_days: 30
  cache_historical: true

# Reporting
reporting:
  # Performance Reports
  generate_daily_report: true
  generate_trade_log: true

  # Report Destinations
  report_email: "${ADMIN_EMAIL}"
  report_s3_bucket: "${REPORT_BUCKET}"

  # Report Content
  include_metrics:
    - "pnl"
    - "sharpe_ratio"
    - "win_rate"
    - "max_drawdown"
    - "total_trades"
    - "error_count"

# Emergency Controls
emergency:
  # Kill Switch
  kill_switch_enabled: true
  kill_switch_key: "${KILL_SWITCH_KEY}"

  # Emergency Contacts
  emergency_phone: "${EMERGENCY_PHONE}"
  emergency_email: "${EMERGENCY_EMAIL}"

  # Liquidation Settings
  emergency_liquidation:
    enabled: true
    trigger: "manual"  # Require manual trigger
    use_market_orders: false  # Still use limits in emergency

# Deployment Notes
notes: |
  This canary profile is configured for Phase 3.2/3.3 Sandbox Soak Test:
  - Coinbase Sandbox environment (no real funds)
  - BTC-USD spot trading with reduce-only mode
  - Maximum $10 daily loss limit
  - Maximum $100 per trade (max_trade_value guard)
  - Single position of 0.01 BTC maximum
  - 24/7 trading window for continuous testing
  - WebSocket streaming enabled with REST fallback
  - Comprehensive metrics and event recording

  Soak Test Objectives:
  1. Validate guardrails (order caps, daily loss, circuit breaker)
  2. Test streaming resilience and REST fallback
  3. Verify Prometheus alerts fire correctly
  4. Measure system stability over 24-48 hours
  5. Collect baseline metrics for production readiness

  Success Criteria:
  - 100% guardrail reliability (no bypasses)
  - >99% streaming uptime with graceful degradation
  - 100% alert accuracy (no false positives/negatives)
  - Zero crashes or deadlocks
  - Memory usage stable (no leaks)
