max_leverage: 5
leverage_max_per_symbol:
  BTC-PERP: 5
  ETH-PERP: 5
  SOL-PERP: 3
  XRP-PERP: 3
daytime_start_utc: '13:00'
daytime_end_utc: '20:00'
day_leverage_max_per_symbol:
  BTC-PERP: 10
  ETH-PERP: 8
  SOL-PERP: 5
  XRP-PERP: 5
night_leverage_max_per_symbol:
  BTC-PERP: 5
  ETH-PERP: 5
  SOL-PERP: 3
  XRP-PERP: 3
min_liquidation_buffer_pct: 0.15
enable_pre_trade_liq_projection: true
default_maintenance_margin_rate: 0.005
daily_loss_limit: '50'
max_exposure_pct: 0.5
max_position_pct_per_symbol: 0.2
max_notional_per_symbol:
  BTC-PERP: '25000'
  ETH-PERP: '15000'
  SOL-PERP: '7500'
  XRP-PERP: '3000'
slippage_guard_bps: 30
kill_switch_enabled: false
reduce_only_mode: false
max_mark_staleness_seconds: 120
enable_volatility_circuit_breaker: false
max_intraday_volatility_threshold: 0.15
volatility_window_periods: 20
circuit_breaker_cooldown_minutes: 30
volatility_warning_threshold: 0.15
volatility_reduce_only_threshold: 0.2
volatility_kill_switch_threshold: 0.25
