apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-autoscaler
  namespace: gpt-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-autoscaler
  template:
    metadata:
      labels:
        app: market-autoscaler
    spec:
      serviceAccountName: market-autoscaler
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: autoscaler
          image: gpt-trader/autoscaler:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gpt-trader-secrets
                  key: REDIS_PASSWORD
            - name: KUBERNETES_NAMESPACE
              value: "gpt-trader"
            - name: SCALING_ENABLED
              value: "true"
            - name: MAX_HOURLY_COST
              value: "100"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: gpt-trader-config

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-autoscaler
  namespace: gpt-trader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: market-autoscaler
  namespace: gpt-trader
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: market-autoscaler
  namespace: gpt-trader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: market-autoscaler
subjects:
  - kind: ServiceAccount
    name: market-autoscaler
    namespace: gpt-trader

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoscaler-policies
  namespace: gpt-trader
data:
  policies.yaml: |
    market_conditions:
      quiet:
        volatility_threshold: 0.2
        volume_threshold: 1000000
        resource_multiplier: 0.5

      normal:
        volatility_threshold: 0.5
        volume_threshold: 5000000
        resource_multiplier: 1.0

      active:
        volatility_threshold: 1.0
        volume_threshold: 20000000
        resource_multiplier: 2.0

      volatile:
        volatility_threshold: 2.0
        volume_threshold: 50000000
        resource_multiplier: 3.0

      extreme:
        volatility_threshold: 5.0
        volume_threshold: 100000000
        resource_multiplier: 5.0

    scaling_targets:
      api-gateway:
        min_replicas: 3
        max_replicas: 20
        scale_factor: 1.5

      trading-engine:
        min_replicas: 2
        max_replicas: 10
        scale_factor: 1.2

      data-pipeline:
        min_replicas: 3
        max_replicas: 20
        scale_factor: 2.0

      ml-inference:
        min_replicas: 2
        max_replicas: 8
        scale_factor: 1.0
