apiVersion: v1
kind: ConfigMap
metadata:
  name: gpt-trader-config
  namespace: gpt-trader
data:
  # Trading Configuration
  trading.yaml: |
    exchange:
      alpaca:
        api_key_id: ${ALPACA_API_KEY_ID}
        api_secret: ${ALPACA_API_SECRET}
        base_url: https://paper-api.alpaca.markets
      polygon:
        api_key: ${POLYGON_API_KEY}
    
    portfolio:
      initial_capital: 100000
      max_position_size: 0.1
      risk_per_trade: 0.02
      max_drawdown: 0.15
    
    strategies:
      - name: transformer_momentum
        enabled: true
        allocation: 0.3
        symbols: ["AAPL", "GOOGL", "MSFT"]
      - name: rl_adaptive
        enabled: true
        allocation: 0.3
        symbols: ["SPY", "QQQ"]
      - name: trend_breakout
        enabled: true
        allocation: 0.2
        symbols: ["TSLA", "NVDA"]
    
  # ML Models Configuration  
  models.yaml: |
    transformer:
      d_model: 512
      n_heads: 8
      n_layers: 6
      dropout: 0.1
      max_sequence_length: 100
      batch_size: 32
      device: cuda
    
    reinforcement:
      algorithm: ppo
      learning_rate: 0.0003
      gamma: 0.99
      episodes: 1000
      update_frequency: 128
    
  # Monitoring Configuration
  monitoring.yaml: |
    metrics:
      prometheus:
        enabled: true
        port: 9090
        retention: 30d
      
    alerts:
      slack:
        webhook_url: ${SLACK_WEBHOOK_URL}
        channel: "#trading-alerts"
      email:
        smtp_host: smtp.gmail.com
        smtp_port: 587
        from: alerts@gpt-trader.com
        to: 
          - ops@gpt-trader.com
    
    thresholds:
      max_drawdown: 0.10
      min_sharpe_ratio: 1.0
      max_position_concentration: 0.25
      
  # Auto-scaling Configuration
  scaling.yaml: |
    policies:
      - name: quiet_market
        min_workers: 2
        max_workers: 5
        target_cpu: 50
        scale_down_cooldown: 300
      - name: normal_market
        min_workers: 5
        max_workers: 10
        target_cpu: 60
        scale_down_cooldown: 180
      - name: active_market
        min_workers: 10
        max_workers: 20
        target_cpu: 70
        scale_down_cooldown: 60
      - name: extreme_market
        min_workers: 20
        max_workers: 50
        target_cpu: 80
        scale_down_cooldown: 30
    
    cost_limits:
      max_hourly_cost: 100
      max_daily_cost: 2000
      max_monthly_cost: 50000