apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-pipeline
  namespace: gpt-trader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-pipeline
  template:
    metadata:
      labels:
        app: data-pipeline
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: data-pipeline
          image: gpt-trader/data-pipeline:latest
          imagePullPolicy: Always
          env:
            - name: ALPACA_API_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gpt-trader-secrets
                  key: ALPACA_API_KEY_ID
            - name: ALPACA_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: gpt-trader-secrets
                  key: ALPACA_API_SECRET
            - name: POLYGON_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gpt-trader-secrets
                  key: POLYGON_API_KEY
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@redis:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gpt-trader-secrets
                  key: REDIS_PASSWORD
            - name: KAFKA_BROKERS
              value: "kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
            - name: DATA_SOURCES
              value: "alpaca,polygon,binance"
            - name: BUFFER_SIZE
              value: "100000"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: gpt-trader-config

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-pipeline-hpa
  namespace: gpt-trader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-pipeline
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 3
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
