version: '1.0'
last_updated: '2025-08-17'
description: Conservative configuration - prioritizes capital preservation over growth
tiers:
  micro:
    name: Micro Portfolio (Conservative)
    range:
    - 500
    - 2500
    positions:
      min: 2
      max: 2
      target: 2
    min_position_size: 200
    strategies:
    - momentum
    risk:
      daily_limit_pct: 0.5
      quarterly_limit_pct: 5.0
      position_stop_loss_pct: 4.0
      max_sector_exposure_pct: 40.0
    trading:
      max_trades_per_week: 2
      account_type: cash
      settlement_days: 2
      pdt_compliant: true
  small:
    name: Small Portfolio (Conservative)
    range:
    - 2500
    - 10000
    positions:
      min: 3
      max: 4
      target: 3
    min_position_size: 600
    strategies:
    - momentum
    risk:
      daily_limit_pct: 1.0
      quarterly_limit_pct: 8.0
      position_stop_loss_pct: 5.0
      max_sector_exposure_pct: 50.0
    trading:
      max_trades_per_week: 4
      account_type: cash
      settlement_days: 2
      pdt_compliant: true
  medium:
    name: Medium Portfolio (Conservative)
    range:
    - 10000
    - 25000
    positions:
      min: 4
      max: 6
      target: 5
    min_position_size: 1500
    strategies:
    - momentum
    - mean_reversion
    risk:
      daily_limit_pct: 1.5
      quarterly_limit_pct: 12.0
      position_stop_loss_pct: 6.0
      max_sector_exposure_pct: 60.0
    trading:
      max_trades_per_week: 6
      account_type: margin
      settlement_days: 0
      pdt_compliant: true
  large:
    name: Large Portfolio (Conservative)
    range:
    - 25000
    - 999999999
    positions:
      min: 6
      max: 10
      target: 8
    min_position_size: 2000
    strategies:
    - momentum
    - mean_reversion
    - trend_following
    risk:
      daily_limit_pct: 2.0
      quarterly_limit_pct: 15.0
      position_stop_loss_pct: 7.0
      max_sector_exposure_pct: 70.0
    trading:
      max_trades_per_week: 10
      account_type: margin
      settlement_days: 0
      pdt_compliant: false
costs:
  commission_per_trade: 0.0
  spread_estimate_pct: 0.05
  slippage_pct: 0.1
  financing_rate_annual_pct: 8.0
validation:
  min_account_size: 500
  max_positions_any_tier: 15
  max_daily_risk_any_tier: 3.0
  min_position_size_any_tier: 200
  max_position_size_pct: 20.0
market_constraints:
  min_share_price: 10.0
  max_share_price: 800.0
  min_daily_volume: 500000
  excluded_sectors:
  - Cryptocurrency
  - Penny Stocks
  excluded_symbols:
  - PENNY
  - OTC
  - PINK
  market_hours_only: true
rebalancing:
  frequency_days: 14
  threshold_pct: 15.0
  tier_transition_buffer_pct: 8.0
