version: '1.0'
description: Global system configuration for GPT-Trader V2
last_updated: '2025-08-19'
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: var/logs/perps_bot.log
  max_bytes: 10485760
  backup_count: 5
  console_output: true
data_provider:
  default: yfinance
  fallback: mock
  cache_enabled: true
  cache_ttl_seconds: 300
  max_cache_size_mb: 100
error_handling:
  max_retries: 3
  retry_delay: 1.0
  exponential_backoff: true
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60.0
performance:
  parallel_workers: 4
  batch_size: 100
  memory_limit_mb: 1024
  timeout_seconds: 300
market:
  timezone: US/Eastern
  market_open: 09:30
  market_close: '16:00'
  trading_days:
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
paths:
  data_dir: data
  cache_dir: cache
  logs_dir: logs
  models_dir: models
  results_dir: results
