groups:
  - name: database_alerts
    interval: 30s
    rules:
      - alert: HighDatabaseLatency
        expr: histogram_quantile(0.99, rate(postgres_query_duration_seconds_bucket[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database query latency"
          description: "P99 query latency is {{ $value }}s (threshold: 100ms)"
      
      - alert: DatabaseConnectionPoolExhausted
        expr: postgres_connections_active / (postgres_connections_active + postgres_connections_idle) > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "{{ $value | humanizePercentage }} of connections in use"
      
      - alert: DatabaseDown
        expr: up{job="postgresql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL has been down for more than 1 minute"

  - name: data_pipeline_alerts
    interval: 30s
    rules:
      - alert: HighDataRejectionRate
        expr: rate(datafeed_messages_rejected_total[5m]) / rate(datafeed_messages_received_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High data rejection rate"
          description: "{{ $value | humanizePercentage }} of messages being rejected"
      
      - alert: DataSourceFailure
        expr: datasource_status{status="unavailable"} == 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Data source {{ $labels.source }} is unavailable"
          description: "Data source has been unavailable for 5 minutes"
      
      - alert: AllDataSourcesDown
        expr: count(datasource_status{status="active"}) == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "All data sources are down"
          description: "No active data sources available"
      
      - alert: LowCacheHitRate
        expr: redis_cache_hit_rate < 0.3
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }} (expected > 30%)"

  - name: performance_alerts
    interval: 30s
    rules:
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / 1024 / 1024 > 2048
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Process using {{ $value }}MB of memory (threshold: 2GB)"
      
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage at {{ $value | humanizePercentage }}"
      
      - alert: LowThroughput
        expr: rate(datafeed_messages_received_total[5m]) < 10
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Low message throughput"
          description: "Receiving only {{ $value }} messages per second"

  - name: ml_model_alerts
    interval: 60s
    rules:
      - alert: ModelAccuracyDegraded
        expr: ml_model_accuracy < 0.5
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Model {{ $labels.model_name }} accuracy degraded"
          description: "Model accuracy is {{ $value | humanizePercentage }} (threshold: 50%)"
      
      - alert: ModelPredictionFailures
        expr: rate(ml_prediction_errors_total[5m]) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High ML prediction error rate"
          description: "{{ $value }} prediction errors per second"
      
      - alert: ModelNotUpdated
        expr: (time() - ml_model_last_updated_timestamp) / 3600 > 24
        for: 1h
        labels:
          severity: info
        annotations:
          summary: "Model {{ $labels.model_name }} not updated"
          description: "Model hasn't been updated for {{ $value }} hours"

  - name: trading_alerts
    interval: 30s
    rules:
      - alert: HighPositionRisk
        expr: position_risk_score > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High risk position detected"
          description: "Position {{ $labels.symbol }} has risk score {{ $value }}"
      
      - alert: OrderExecutionFailures
        expr: rate(order_execution_failures_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High order execution failure rate"
          description: "{{ $value }} order failures per second"
      
      - alert: PortfolioDrawdown
        expr: portfolio_drawdown_percent > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Portfolio drawdown exceeds threshold"
          description: "Portfolio down {{ $value }}% from peak"

  - name: system_health_alerts
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute"
      
      - alert: HighErrorRate
        expr: rate(errors_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High system error rate"
          description: "{{ $value }} errors per second"
      
      - alert: DiskSpaceLow
        expr: node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Only {{ $value | humanizePercentage }} disk space remaining"