version: '1.0'
last_updated: '2025-08-17'
description: Aggressive configuration - prioritizes growth with higher risk tolerance
tiers:
  micro:
    name: Micro Portfolio (Aggressive)
    range:
    - 500
    - 2500
    positions:
      min: 2
      max: 3
      target: 3
    min_position_size: 150
    strategies:
    - momentum
    - mean_reversion
    risk:
      daily_limit_pct: 2.0
      quarterly_limit_pct: 15.0
      position_stop_loss_pct: 8.0
      max_sector_exposure_pct: 70.0
    trading:
      max_trades_per_week: 5
      account_type: cash
      settlement_days: 2
      pdt_compliant: true
  small:
    name: Small Portfolio (Aggressive)
    range:
    - 2500
    - 10000
    positions:
      min: 3
      max: 6
      target: 5
    min_position_size: 400
    strategies:
    - momentum
    - mean_reversion
    - trend_following
    risk:
      daily_limit_pct: 2.5
      quarterly_limit_pct: 18.0
      position_stop_loss_pct: 10.0
      max_sector_exposure_pct: 80.0
    trading:
      max_trades_per_week: 8
      account_type: cash
      settlement_days: 2
      pdt_compliant: true
  medium:
    name: Medium Portfolio (Aggressive)
    range:
    - 10000
    - 25000
    positions:
      min: 5
      max: 10
      target: 8
    min_position_size: 1000
    strategies:
    - momentum
    - mean_reversion
    - trend_following
    - ml_enhanced
    risk:
      daily_limit_pct: 3.0
      quarterly_limit_pct: 25.0
      position_stop_loss_pct: 12.0
      max_sector_exposure_pct: 90.0
    trading:
      max_trades_per_week: 15
      account_type: margin
      settlement_days: 0
      pdt_compliant: true
  large:
    name: Large Portfolio (Aggressive)
    range:
    - 25000
    - 999999999
    positions:
      min: 8
      max: 20
      target: 15
    min_position_size: 1200
    strategies:
    - momentum
    - mean_reversion
    - trend_following
    - ml_enhanced
    risk:
      daily_limit_pct: 4.0
      quarterly_limit_pct: 30.0
      position_stop_loss_pct: 15.0
      max_sector_exposure_pct: 100.0
    trading:
      max_trades_per_week: 999
      account_type: margin
      settlement_days: 0
      pdt_compliant: false
costs:
  commission_per_trade: 0.0
  spread_estimate_pct: 0.05
  slippage_pct: 0.15
  financing_rate_annual_pct: 8.0
validation:
  min_account_size: 500
  max_positions_any_tier: 25
  max_daily_risk_any_tier: 6.0
  min_position_size_any_tier: 100
  max_position_size_pct: 30.0
market_constraints:
  min_share_price: 3.0
  max_share_price: 2000.0
  min_daily_volume: 50000
  excluded_sectors: []
  excluded_symbols:
  - PINK
  market_hours_only: false
rebalancing:
  frequency_days: 3
  threshold_pct: 5.0
  tier_transition_buffer_pct: 3.0
