#!/usr/bin/env python3
"""Build script to concatenate TUI CSS modules into main.tcss.

Textual doesn't support CSS @import, so we concatenate modules at build time.
Run this script after modifying any CSS module files.

Usage:
    python scripts/build_tui_css.py
    # or
    uv run python scripts/build_tui_css.py
"""

from pathlib import Path

# CSS module loading order (dependencies first)
CSS_MODULE_ORDER = [
    # 1. Theme variables (must be first - defines all $variables)
    "theme/variables.tcss",
    # 2. Layout (screen structure)
    "layout/screen.tcss",
    "layout/workspace.tcss",
    # 3. Components (reusable UI elements)
    "components/focus.tcss",
    "components/headers.tcss",
    "components/buttons.tcss",
    "components/tables.tcss",
    "components/tabs.tcss",
    "components/select.tcss",
    "components/utilities.tcss",
    "components/animations.tcss",
    # 4. Widgets (specific widget styles)
    "widgets/status_bar.tcss",
    "widgets/account.tcss",
    "widgets/portfolio.tcss",
    "widgets/market.tcss",
    "widgets/logs.tcss",
    "widgets/modals.tcss",
    "widgets/execution.tcss",
    "widgets/error_indicator.tcss",
    # 5. Screens (screen-specific overrides)
    "screens/mode_selection.tcss",
]

# Header for generated file
GENERATED_HEADER = """\
/* ============================================================================ */
/* GENERATED FILE - DO NOT EDIT DIRECTLY                                        */
/* ============================================================================ */
/*                                                                              */
/* This file is auto-generated by scripts/build_tui_css.py                     */
/* Edit the source modules in styles/ subdirectories instead:                   */
/*   - theme/       : Theme variables and colors                                */
/*   - layout/      : Screen and workspace layout                               */
/*   - components/  : Reusable UI components                                    */
/*   - widgets/     : Widget-specific styles                                    */
/*   - screens/     : Screen-specific styles                                    */
/*                                                                              */
/* To regenerate: python scripts/build_tui_css.py                               */
/*                                                                              */
/* ============================================================================ */

"""


def get_section_header(module_path: str) -> str:
    """Generate a section header comment for a module."""
    # Extract category and name
    parts = module_path.replace(".tcss", "").split("/")
    if len(parts) == 2:
        category, name = parts
        title = f"{category.upper()}: {name.replace('_', ' ').title()}"
    else:
        title = module_path.replace(".tcss", "").upper()

    return f"""
/* ---------------------------------------------------------------------------- */
/* {title:<74} */
/* Source: styles/{module_path:<60} */
/* ---------------------------------------------------------------------------- */

"""


def build_css(styles_dir: Path, output_file: Path) -> tuple[int, int, list[str]]:
    """Concatenate CSS modules into single output file.

    Returns:
        Tuple of (modules_found, total_lines, missing_modules)
    """
    modules_found = 0
    total_lines = 0
    missing_modules: list[str] = []
    output_parts: list[str] = [GENERATED_HEADER]

    for module_path in CSS_MODULE_ORDER:
        full_path = styles_dir / module_path

        if not full_path.exists():
            missing_modules.append(module_path)
            continue

        content = full_path.read_text()
        line_count = len(content.splitlines())

        # Add section header and content
        output_parts.append(get_section_header(module_path))
        output_parts.append(content)
        output_parts.append("\n")

        modules_found += 1
        total_lines += line_count

    # Write output
    output_file.write_text("".join(output_parts))

    return modules_found, total_lines, missing_modules


def main() -> int:
    """Main entry point."""
    # Find project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent

    styles_dir = project_root / "src" / "gpt_trader" / "tui" / "styles"
    output_file = styles_dir / "main.tcss"

    if not styles_dir.exists():
        print(f"Error: Styles directory not found: {styles_dir}")
        return 1

    print(f"Building TUI CSS from modules in {styles_dir}")
    print("-" * 60)

    modules_found, total_lines, missing = build_css(styles_dir, output_file)

    print(f"Modules processed: {modules_found}/{len(CSS_MODULE_ORDER)}")
    print(f"Total lines: {total_lines}")
    print(f"Output: {output_file}")

    if missing:
        print(f"\nWarning: {len(missing)} modules not found (will be skipped):")
        for m in missing:
            print(f"  - {m}")

    print("-" * 60)
    print("CSS build complete!")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
