name: derivatives-phase6

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-derivatives-phase6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.12-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run perps validation harness
        env:
          EVENT_STORE_ROOT: ${{ runner.temp }}/event_store_validation
        run: |
          mkdir -p "$EVENT_STORE_ROOT"
          poetry run python scripts/validation/validate_perps_e2e.py

      - name: Run tightening guard tests
        run: |
          poetry run pytest \
            tests/unit/bot_v2/features/live_trade/test_reduce_only_guard.py \
            tests/unit/bot_v2/features/live_trade/test_trailing_stop_decision.py \
            tests/unit/bot_v2/features/live_trade/test_leverage_cap.py \
            tests/unit/bot_v2/features/brokerages/coinbase/test_quantization_rules.py \
            -q --tb=short

      - name: Verify adapter integration
        run: |
          poetry run pytest tests/unit/bot_v2/features/brokerages/coinbase/test_adapter_integration.py -v
