name: derivatives-phase6

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  validate-derivatives-phase6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Prepare Python environment
        id: setup-poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.12"

      - name: Run perps validation harness
        env:
          EVENT_STORE_ROOT: ${{ runner.temp }}/event_store_validation
        run: |
          mkdir -p "$EVENT_STORE_ROOT"
          poetry run python scripts/validation/validate_perps_e2e.py

      - name: Run tightening guard tests
        run: |
          poetry run pytest \
            tests/unit/bot_v2/features/live_trade/test_reduce_only_guard.py \
            tests/unit/bot_v2/features/live_trade/test_trailing_stop_decision.py \
            tests/unit/bot_v2/features/live_trade/test_leverage_cap.py \
            tests/unit/bot_v2/features/brokerages/coinbase/test_specs_quantization.py \
            -q --tb=short

      - name: Verify adapter integration
        run: |
          poetry run pytest tests/unit/bot_v2/features/brokerages/coinbase/test_adapter_integration.py -v
