name: derivatives-phase6

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  validate-derivatives-phase6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run perps validation harness
        env:
          EVENT_STORE_ROOT: ${{ runner.temp }}/event_store_validation
        run: |
          mkdir -p "$EVENT_STORE_ROOT"
          poetry run python scripts/validation/validate_perps_e2e.py

      - name: Run tightening guard tests
        run: |
          poetry run pytest \
            tests/unit/bot_v2/features/live_trade/test_reduce_only_guard.py \
            tests/unit/bot_v2/features/live_trade/test_trailing_stop_decision.py \
            tests/unit/bot_v2/features/live_trade/test_leverage_cap.py \
            tests/unit/bot_v2/features/brokerages/coinbase/test_specs_quantization.py \
            -q --tb=short

      - name: Verify adapter integration
        run: |
          poetry run pytest tests/unit/bot_v2/features/brokerages/coinbase/test_adapter_integration.py -v
