name: Nightly Tests

on:
  schedule:
    - cron: "0 2 * * *" # Every day at 2 AM UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  full-test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v5

    - name: Prepare Python environment
      id: setup-poetry
      uses: ./.github/actions/setup-poetry
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run full test suite (including slow tests)
      run: |
        poetry run pytest
