name: Nightly Full Suite

on:
  schedule:
    - cron: "0 2 * * *" # Every day at 2 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash --noprofile --norc

env:
  PYTHON_VERSION: "3.12"

jobs:
  full-test-suite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Prepare Python environment
      id: setup-poetry
      uses: ./.github/actions/setup-poetry
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Run full test suite (including slow tests)
      run: |
        set -euo pipefail
        poetry run pytest
