name: Perps Validation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash --noprofile --norc {0}

env:
  PYTHON_VERSION: "3.12"

jobs:
  perps-validation:
    name: Derivatives/Perps Health
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Prepare Python environment
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run perps validation harness
        env:
          EVENT_STORE_ROOT: ${{ runner.temp }}/event_store_validation
        run: |
          set -euo pipefail
          mkdir -p "$EVENT_STORE_ROOT"
          poetry run python scripts/validation/validate_perps_e2e.py

      - name: Run tightening guard tests
        run: |
          set -euo pipefail
          poetry run pytest \
            tests/unit/bot_v2/features/live_trade/test_reduce_only_guard.py \
            tests/unit/bot_v2/features/live_trade/test_trailing_stop_decision.py \
            tests/unit/bot_v2/features/live_trade/test_leverage_cap.py \
            tests/unit/bot_v2/features/brokerages/coinbase/test_specs_quantization.py \
            -q --tb=short

      - name: Verify adapter integration
        run: |
          set -euo pipefail
          poetry run pytest tests/unit/bot_v2/features/brokerages/coinbase/test_adapter_integration.py -v
