name: security-audit
on:
  schedule:
    - cron: "0 6 * * 1" # weekly, Mondays 06:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare Python environment
        uses: ./.github/actions/setup-poetry
        with:
          python-version: "3.12"
          install-deps: "false"
          cache-path: ""
      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit
      - name: Install project (no dev)
        run: |
          poetry export -f requirements.txt --with main --without-hashes -o requirements.txt
      - name: Run pip-audit (fail on high/critical)
        run: pip-audit --strict
