name: Security Audit
on:
  schedule:
    - cron: "0 6 * * 1" # weekly, Mondays 06:00 UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash --noprofile --norc

env:
  PYTHON_VERSION: "3.12"

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Prepare Python environment
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          install-deps: "false"
          cache-path: ""
      - name: Install pip-audit
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip pip-audit
      - name: Install project (no dev)
        run: |
          set -euo pipefail
          poetry export -f requirements.txt --with main --without-hashes -o requirements.txt
      - name: Run pip-audit (fail on high/critical)
        run: |
          set -euo pipefail
          pip-audit -r requirements.txt --strict
