name: security-audit
on:
  schedule:
    - cron: "0 6 * * 1" # weekly, Mondays 06:00 UTC
  workflow_dispatch:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: "3.12" }
      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit
      - name: Install project (no dev)
        run: |
          python -m pip install poetry
          poetry export -f requirements.txt --with main --without-hashes -o requirements.txt
      - name: Run pip-audit (fail on high/critical)
        run: pip-audit --strict
